print("Personal Info Card Generator")

f_n = input("Enter your full name: ")
age = input("Enter your age: ")
country = input("Enter your country: ")
email = input("Enter your email: ")
phone = input("Enter your phone number: ")

print("\n" + "="*30)
print("       PERSONAL INFO CARD       ")
print("="*30)
print(f"Name       : {f_n}")
print(f"Age        : {age}")
print(f"Country    : {country}")
print(f"Email      : {email}")
print(f"Phone      : {phone}")
print("="*30)
